settings:
  disabled-worlds:
  - world_meridia
  save-interval: 60
database:
  type: mysql
  mysql:
    host: localhost
    port: 3306
    username: root
    password: root
    database: elchilen0
  sqlite:
    file: data.dat
