settings:
  disabled-worlds:
  - world_meridia
  save-interval: 60
database:
  type: mysql
  mysql:
    username: root
    password: root
    port: 3601
    database: minecraft
  sqlite:
    file: data.dat
