name: Supernaturals
version: 2.0.5
author: ELCHILEN0
description: Bring a RPG experience to Minecraft!
website: http://www.novuscraft.org
main: com.TeamNovus.Supernaturals.Supernaturals
commands:
  supernaturals:
    aliases: [supernatural, sn]