name: Supernaturals
author: ELCHILEN0
description: Bring a RPG experience to Minecraft!
version: 2.0.0
main: com.TeamNovus.Supernaturals.Supernaturals
commands:
  supernaturals:
    aliases: [supernatural, sn]